-- Enum Types and Implicit Casts
CREATE TYPE CustomerRole AS ENUM ('ADMIN', 'USER');
CREATE CAST (varchar AS CustomerRole) WITH INOUT AS IMPLICIT;
CREATE CAST (CustomerRole AS varchar) WITH INOUT AS IMPLICIT;

CREATE TYPE OrderSide AS ENUM ('BUY', 'SELL');
CREATE CAST (varchar AS OrderSide) WITH INOUT AS IMPLICIT;
CREATE CAST (OrderSide AS varchar) WITH INOUT AS IMPLICIT;

CREATE TYPE OrderStatus AS ENUM ('PENDING', 'MATCHED', 'CANCELED');
CREATE CAST (varchar AS OrderStatus) WITH INOUT AS IMPLICIT;
CREATE CAST (OrderStatus AS varchar) WITH INOUT AS IMPLICIT;

-- Table: customer
CREATE TABLE IF NOT EXISTS customer
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    password VARCHAR(255) NOT NULL,
    role     CustomerRole,
    username VARCHAR(255) NOT NULL CONSTRAINT uq_customer_username UNIQUE
);

-- Table: asset
CREATE TABLE IF NOT EXISTS asset
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_name   VARCHAR(255) NOT NULL,
    size         DOUBLE PRECISION NOT NULL,
    usable_size  DOUBLE PRECISION NOT NULL,
    customer_id  BIGINT NOT NULL CONSTRAINT fk_asset_customer REFERENCES customer
);

-- Indexes on asset table
CREATE INDEX IF NOT EXISTS idx_asset_name ON asset (asset_name);

-- Table: orders
CREATE TABLE IF NOT EXISTS orders
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_name  VARCHAR(255),
    create_date TIMESTAMP(6),
    order_side  OrderSide,
    price       DOUBLE PRECISION NOT NULL,
    size        INTEGER NOT NULL,
    status      OrderStatus NOT NULL,
    version     INT NOT NULL,
    customer_id BIGINT NOT NULL CONSTRAINT fk_orders_customer REFERENCES customer
);